namespace WristbandRadio.FileServer.Submissions.Application.MusicSubmissions.Queries.GetPaginatedMusicSubmissions;

public record GetPaginatedMusicSubmissionsQuery(MusicSubmissionQueryParameters QueryParameters) : IRequest<PageList<MusicSubmissionResponseDto>>;
