namespace WristbandRadio.FileServer.Submissions.Application.MusicSubmissions.Queries.GetPaginatedMusicSubmissionsByStatus;

public sealed record GetPaginatedMusicSubmissionsByStatusQuery(MusicSubmissionQueryParameters QueryParameters, string Status) : IRequest<PageList<MusicSubmissionResponseDto>>;
