namespace WristbandRadio.FileServer.Submissions.Application.FeedbackSubmissions.Queries.GetPaginatedFeedbackSubmissions;

public sealed record GetPaginatedFeedbackSubmissionsQuery(FeedbackSubmissionQueryParameters QueryParameters) : IRequest<PageList<FeedbackSubmissionResponseDto>>;
