namespace WristbandRadio.FileServer.Submissions.Application.FeedbackSubmissions.Queries.GetPaginatedFeedbackSubmissionsByStatus;

public sealed record GetPaginatedFeedbackSubmissionsByStatusQuery(FeedbackSubmissionQueryParameters QueryParameters, string Status) : IRequest<PageList<FeedbackSubmissionResponseDto>>;
